language: node_js
node_js:
  - 5.0.0
branches:
  only: 'master'
before_install:
  - npm install -g bower coffee-script browserify
before_script:
  - npm run init
script:
  - echo "nothing"
after_script:
  - mkdir tmp
  - mkdir tmp/dist
  - \cp -f -R dist/ukapre.js tmp/dist
  - git stash
  - rm -rf bower_components
  - git config remote.origin.fetch "+refs/heads/gh-pages:refs/remotes/origin/gh-pages"
  - git fetch origin gh-pages
  - git checkout gh-pages
  - \cp -f -R tmp/dist/* ./ukapre.js
  - git add ukapre.js
  - git status
  - git commit -am "travis-auto-update"
  - git ls-files
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ $GH_TOKEN ] && git push --force --quiet "https://${GH_TOKEN}@github.com/legokichi/ukagaka-preview.git" gh-pages:gh-pages > /dev/null 2>&1'
env:
  global:
    - GIT_COMMITTER_NAME=legokichi
    - GIT_COMMITTER_EMAIL=legokichi@gmail.com
    - GIT_AUTHOR_NAME=legokichi
    - GIT_AUTHOR_EMAIL=legokichi@gmail.com
    - secure: "Qb4ImvPXMDvTX4tVQ16BxfaZZ8NUGWFsmwDT/Zgb4L2rWT8mPb4SXPe9wjazmzqW9AdxnQ4V1reuVfVhIxcu21nxzYDxnc1+IyJ4dhISRoi80994iOfhllfjztZLUDzRZBcyO475IEgpD+v2V5KzAbafpfoZRLgemIxFQmjvhOw="
